apiVersion: v1
data:
  configuration: eyJhdXRoVHlwZSI6IkJBU0lDX0FVVEgiLCJjcmVkZW50aWFscyI6eyJ1c2VybmFtZSI6IiIsInBhc3N3b3JkIjoiIn19Cg==
kind: Secret
metadata:
  name: github-ivt-secret
---
apiVersion: appconnect.ibm.com/v1beta1
kind: Configuration
metadata:
  name: github-ivt
spec:
  secretName: github-ivt-secret
  type: barauth
---
apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationRuntime
metadata:
  name: ace-ivt104
  labels:
    backup.appconnect.ibm.com/component: integrationruntime
  namespace: cp4i
spec:
  license:
    accept: true
    license: L-KPRV-AUG9NC
    use: CloudPakForIntegrationNonProductionFREE
  template:
    spec:
      containers:
        - resources:
            requests:
              cpu: 300m
              memory: 368Mi
          name: runtime
  logFormat: basic
  barURL:
    - 'https://github.com/nmsaini/tekton-pipeline-test/raw/main/deploy/IVT.104.bar'
  configurations:
    - github-ivt
  defaultNetworkPolicy:
    enabled: true
  replicas: 1
  version: '13.0'
# curl -s $(oc get routes ace-ivt104-http -o jsonpath="{.spec.host}")/IVT?delay=1;echo
