apiVersion: appconnect.ibm.com/v1beta1
kind: Dashboard
metadata:
  name: ace-dash
  namespace: cp4i
spec:
  license:
    accept: true
    license: L-XRNH-47FJAW
    use: CloudPakForIntegrationNonProduction
  pod:
    containers:
      content-server:
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 50Mi
      control-ui:
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 125Mi
  authentication:
    integrationKeycloak:
      enabled: true
  authorization:
    integrationKeycloak:
      enabled: true
  api:
    enabled: true
  storage:
    size: 5Gi
    type: persistent-claim
    class: ocs-storagecluster-cephfs
  replicas: 1
  displayMode: IntegrationRuntimes
  version: '12.0'
